name: Run Roblox AFK Script

on:
  workflow_dispatch:

jobs:
  afk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run afk.js
        run: node afk.js
