name: Run Roblox AFK Script

on:
  workflow_dispatch:

jobs:
  afk:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # <--- เพิ่มบรรทัดนี้

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run AFK script
        run: node afk.js
